### ISSUE TITLE
Expose experimental features

### ISSUE THREAD

**Issue by emzatos** [software-mansion/TypeGPU#414]
Wanting to use tgpu textures but discovered that's not possible from the npm package. Can the experimental entrypoint be added to the exported package?

**Comment by iwoplaza** [comment]
HI! Thanks for reaching out. We are currently reworking most of the APIs outside of what's public in 0.1, so that it can be used in existing WebGPU projects. We wanted to hold off from introducing tgpu textures until a later date, when they make sense in the context of the public API (currently they cannot even be used through the public API).

Could you describe your use case for them? This will allow us to focus our efforts on what's important for the community.

**Comment by emzatos** [comment]
Thanks for the quick response! Main use case is being able to create storage textures and samplers as easily as tgpu storage buffers. I noticed they were used in the repo so I was hoping there was a way to use them myself, but I can wait for the official release!
